### PR TITLE
Fix filename LICENCE » LICENSE

### PR DESCRIPTION
**Pull request by pelevesque**
I fixed the spelling of the LICENSE filename.

### CODE REVIEW

**Comment by jonathanstowe** [comment]
Hi,
LICENCE is the correct spelling.  LICENSE is a verb whereas LICENCE is the noun.

**Comment by pelevesque** [comment]
Oops! Sorry about that. I only ever saw LICENSE before in github repos. Probably because that is the spelling github uses if you let it generate a license for you. I was also thrown off because all the Raku-Noise-Gang repos use LICENSE except for Audio-PortMIDI and Audio-PortAudio. My English dictionary also disagrees with you, so now I am completely confused!

**Comment by pelevesque** [comment]
Oh gee... It's an America vs UK thing: https://www.grammarly.com/blog/licence-license/

Well, my pull-request was useless, but I did learn something.

**Comment by jonathanstowe** [comment]
It's the US English vs British English thing.  The US has "license" for both noun and verb, whereas British the spellings are distinct .

**Comment by jonathanstowe** [comment]
I blame Noah Webster for this.

**Pull request closed without merging**
